### ISSUE TITLE
Grid layout for charts?

### ISSUE THREAD

**Issue by bulbil** [amy-s-han/lib-lab-swarthmore-women-in-stem#2]

**Comment by bulbil** [comment]
a couple possibilities:

- [column-count](https://developer.mozilla.org/en-US/docs/Web/CSS/column-count)
- implementing grid css like [basscss](http://basscss.com/)
- some kind of float layout

```
<div></div>
<div></div>
<div></div>

styles:

div {
  width: 32% or 300px;
  float: left;
  display: inline-block;
}
```

**Comment by amy-s-han** [comment]
Got basscss to work!
